/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doanjava1;

import doanjava1.Model.KhachHang;
import doanjava1.Model.TinhTrang;
import doanjava1.Model.Xe;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class QuanLyTinhTrangXe extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyKhachHang
     */
    public QuanLyTinhTrangXe() {
        initComponents();
        show_TinhTrang();
    }
    
       public ArrayList<TinhTrang> tinhTrangList(){
        ArrayList<TinhTrang> tinhtrangList = new ArrayList<>();
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String connectionUrl = "jdbc:sqlserver://DESKTOP-QEN4LJI;databaseName=QLTHUEXE;user=sa;password=12";
            Connection con = DriverManager.getConnection(connectionUrl);
            String query ="select b.MAHD,a.MAKH,TENKH,b.MAXE,a.NGAYLAPHD,SONGAYTHUE,TONGTIEN from HOADON a,CT_HOADON b, KH c,XE d where a.MAKH = c.MAKH and b.MAHD = a.MAHD and d.MAXE = b.MAXE and a.MAHD = b.MAHD";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            TinhTrang tinhtrang;
            while(rs.next()){
                tinhtrang= new TinhTrang(rs.getString("MAHD"),rs.getString("MAKH"),rs.getString("TENKH"),
                        rs.getString("MAXE"),rs.getString("NGAYLAPHD"),rs.getString("SONGAYTHUE"),rs.getString("TONGTIEN"));
                tinhtrangList.add(tinhtrang);
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }  
        return tinhtrangList;
    }
               public final void show_TinhTrang(){
        ArrayList<TinhTrang> list = tinhTrangList();
        DefaultTableModel model = (DefaultTableModel)tblTinhTrang.getModel();
        Object[] row = new Object[7];
        for(int i =0;i<list.size();i++)
        {
            row[0] = list.get(i).getMaHD();
            row[1] = list.get(i).getMaKH();
            row[2] = list.get(i).getTenKH();
            row[3] = list.get(i).getMaXe();
            row[4] = list.get(i).getNgayLap();
            row[5] = list.get(i).getSoNgay();
            row[6] = list.get(i).getTien();
    
 
            model.addRow(row);
        }
    }
 
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTinhTrang = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel1.setText("TÌNH TRẠNG CHO THUÊ XE");

        tblTinhTrang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Mã khách hàng", "Tên khách hàng", "Mã xe", "Ngày lập hóa đơn", "Số ngày thuê"
            }
        ));
        jScrollPane1.setViewportView(tblTinhTrang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(300, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(300, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyTinhTrangXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyTinhTrangXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyTinhTrangXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyTinhTrangXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyTinhTrangXe().setVisible(true);
            }
        });
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTinhTrang;
    // End of variables declaration//GEN-END:variables
}
