/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doanjava1;

import doanjava1.Model.KhachHang;
import doanjava1.Model.Xe;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class QuanLyXe extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyXe
     */
     String loai;
    public QuanLyXe() {
        initComponents();
        show_Xe();
    }
      public ArrayList<Xe> xeList(){
        ArrayList<Xe> xeList = new ArrayList<>();
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String connectionUrl = "jdbc:sqlserver://DESKTOP-QEN4LJI;databaseName=QLTHUEXE;user=sa;password=12";
            Connection con = DriverManager.getConnection(connectionUrl);
            String query ="SELECT * FROM XE";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            Xe xe;
            while(rs.next()){
                xe= new Xe(rs.getString("MAXE"),rs.getString("TENXE"),rs.getString("Loai"));
                xeList.add(xe);
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }  
        return xeList;
    }
      
           public final void show_Xe(){
        ArrayList<Xe> list = xeList();
        DefaultTableModel model = (DefaultTableModel)tblXe.getModel();
        Object[] row = new Object[3];
        for(int i =0;i<list.size();i++)
        {
            row[0] = list.get(i).getMaXe();
            row[1] = list.get(i).getTenXe();
            row[2] = list.get(i).getLoai();
 
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnXega = new javax.swing.JRadioButton();
        btnXeso = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaxe = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTenXe = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblXe = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel1.setText("Quản lý xe");

        buttonGroup1.add(btnXega);
        btnXega.setText("Xe ga");
        btnXega.setIconTextGap(10);
        btnXega.setInheritsPopupMenu(true);
        btnXega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXegaActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnXeso);
        btnXeso.setText("Xe số");
        btnXeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXesoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel2.setText("Loại xe");

        jLabel3.setText("Mã xe");

        txtMaxe.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtMaxeInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        jLabel4.setText("Tên xe");

        tblXe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã xe", "Tên xe", "Loại xe"
            }
        ));
        tblXe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblXeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblXe);

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon_yes.png"))); // NOI18N
        btnThem.setText("Thêm xe");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon_no.png"))); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon_Sua.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon_xoaxe.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doanjava1/Close.png"))); // NOI18N
        jButton1.setText("Quay lại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnXega)
                        .addGap(18, 18, 18)
                        .addComponent(btnXeso))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTenXe, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                .addComponent(txtMaxe))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addGap(43, 43, 43)
                                .addComponent(btnHuy)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btnSua)
                        .addGap(49, 49, 49)
                        .addComponent(btnXoa)
                        .addContainerGap(123, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnXeso)
                            .addComponent(btnXega))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtMaxe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTenXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jButton1))
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnHuy)
                    .addComponent(btnSua)
                    .addComponent(btnXoa))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXegaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXegaActionPerformed

    private void btnXesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXesoActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
          try {
            if(txtMaxe.getText().isEmpty()||txtTenXe.getText().isEmpty()
                 )
            {
           JOptionPane.showMessageDialog(null, "Vui lòng nhập đủ thông tin");
        }
           else
            {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String connectionUrl = "jdbc:sqlserver://DESKTOP-QEN4LJI;databaseName=QLTHUEXE;user=sa;password=12";
            Connection con = DriverManager.getConnection(connectionUrl);
            String query  ="INSERT into Xe(MAXE,TENXE,LOAI,TINHTRANG) values (?,?,?,?)";
            PreparedStatement pst = con.prepareCall(query);
            pst.setString(1, txtMaxe.getText().toUpperCase());
            pst.setString(2, txtTenXe.getText());
           
            if(btnXega.isSelected())
            {
                loai="Xe ga";
            }
            
             if(btnXeso.isSelected())
            {
                loai="Xe số";
            }
            pst.setString(3, loai);
            pst.setString(4, "False");

            pst.execute();
           JOptionPane.showMessageDialog(null, "Thêm xe thành công");
           txtMaxe.setText("");
           txtTenXe.setText("");

            DefaultTableModel model = (DefaultTableModel) tblXe.getModel();
            model.setRowCount(0);
            show_Xe();
            }
        } catch (Exception e) {
          JOptionPane.showMessageDialog(null, "Thêm xe không thành công");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
          txtMaxe.setText("");
           txtTenXe.setText("");
    }//GEN-LAST:event_btnHuyActionPerformed

    private void tblXeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblXeMouseClicked
        // TODO add your handling code here:
            int row = tblXe.getSelectedRow();
            String maxe = (tblXe.getModel().getValueAt(row, 0).toString());
            String tenxe = (tblXe.getModel().getValueAt(row, 1).toString());
            String loai1 = (tblXe.getModel().getValueAt(row, 2).toString());
            txtMaxe.setText(maxe);
            txtTenXe.setText(tenxe);
            if(loai1.equals("Xe số"))
            {
                btnXeso.isSelected();
            }
            else
            {
                btnXega.isSelected();
            }
        
    }//GEN-LAST:event_tblXeMouseClicked

    private void txtMaxeInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtMaxeInputMethodTextChanged
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txtMaxeInputMethodTextChanged

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
           try {
            if(txtMaxe.getText().isEmpty()||txtTenXe.getText().isEmpty()
                 )
            {
           JOptionPane.showMessageDialog(null, "Vui lòng nhập đủ thông tin");
        }
           else
            {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String connectionUrl = "jdbc:sqlserver://DESKTOP-QEN4LJI;databaseName=QLTHUEXE;user=sa;password=12";
            Connection con = DriverManager.getConnection(connectionUrl);
             String maXe = txtMaxe.getText().toUpperCase();
            String tenXe = txtTenXe.getText();
               if(btnXega.isSelected())
            {
                loai="Xe ga";
            }
            
             if(btnXeso.isSelected())
            {
                loai="Xe số";
            }
            String query  ="UPDATE XE SET MAXE='"+maXe+"',TENXE='"+tenXe+"',LOAI='"+loai+"' WHERE MAXE='"+maXe +"'";
            PreparedStatement pst = con.prepareCall(query);
            pst.execute();
           JOptionPane.showMessageDialog(null, "Sửa thông tin xe thành công");
           txtMaxe.setText("");
           txtTenXe.setText("");

            DefaultTableModel model = (DefaultTableModel) tblXe.getModel();
            model.setRowCount(0);
            show_Xe();
            }
        } catch (Exception e) {
          JOptionPane.showMessageDialog(null, "Sửa thông xe không thành công");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
         try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String connectionUrl = "jdbc:sqlserver://DESKTOP-QEN4LJI;databaseName=QLTHUEXE;user=sa;password=12";
            Connection con = DriverManager.getConnection(connectionUrl);
             String maXe = txtMaxe.getText().toUpperCase();
            String tenXe = txtTenXe.getText();
               if(btnXega.isSelected())
            {
                loai="Xe ga";
            }
            
             if(btnXeso.isSelected())
            {
                loai="Xe số";
            }
            String query  ="DELETE XE  WHERE MAXE='"+maXe +"'";
            PreparedStatement pst = con.prepareCall(query);
            pst.execute();
           JOptionPane.showMessageDialog(null, "Xóa xe thành công");
           txtMaxe.setText("");
           txtTenXe.setText("");

            DefaultTableModel model = (DefaultTableModel) tblXe.getModel();
            model.setRowCount(0);
            show_Xe();
            
        } catch (Exception e) {
          JOptionPane.showMessageDialog(null, "Xóa xe không thành công");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Menu mn = new Menu();
        mn.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyXe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JRadioButton btnXega;
    private javax.swing.JRadioButton btnXeso;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblXe;
    private javax.swing.JTextField txtMaxe;
    private javax.swing.JTextField txtTenXe;
    // End of variables declaration//GEN-END:variables
}
