/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doanjava1;

import doanjava1.Model.NhanVien;
import doanjava1.Model.Xe;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class QuanLyNhanVien extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyNhanVien
     */
    String gt;
    public QuanLyNhanVien() {
        initComponents();
        show_NV();
    }
    public ArrayList<NhanVien> nvList(){
        ArrayList<NhanVien> nvList = new ArrayList<>();
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String connectionUrl = "jdbc:sqlserver://DESKTOP-QEN4LJI;databaseName=QLTHUEXE;user=sa;password=12";
            Connection con = DriverManager.getConnection(connectionUrl);
            String query ="SELECT * FROM NV";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            NhanVien nv;
            while(rs.next()){
                nv= new NhanVien(rs.getString("MANV"),rs.getString("TENNV"),rs.getString("DIACHI"),rs.getString("SDT")
                ,rs.getString("GT"),rs.getString("LUONG"));
                nvList.add(nv);
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }  
        return nvList;
    }
      
           public final void show_NV(){
        ArrayList<NhanVien> list = nvList();
        DefaultTableModel model = (DefaultTableModel)tblNhanVien.getModel();
        Object[] row = new Object[6];
        for(int i =0;i<list.size();i++)
        {
            row[0] = list.get(i).getMaNV();
            row[1] = list.get(i).getTenNV();
            row[2] = list.get(i).getGT();
            row[3] = list.get(i).getSDT();
            row[4] = list.get(i).getDiaChi();
            row[5] = list.get(i).getLUONG();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        txtTenNV = new javax.swing.JTextField();
        txtSdt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnNam = new javax.swing.JRadioButton();
        btnNu = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDiaChi = new javax.swing.JTextArea();
        txtLuong = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel1.setText("Quản lý nhân viên");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Điền thông tin nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 15))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel2.setText("Mã nhân viên");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel3.setText("Tên nhân viên");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel4.setText("Số điện thoại\\");

            txtTenNV.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    txtTenNVActionPerformed(evt);
                }
            });

            jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
            jLabel5.setText("Giới tính");

            buttonGroup1.add(btnNam);
            btnNam.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
            btnNam.setText("Nam");

            buttonGroup1.add(btnNu);
            btnNu.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
            btnNu.setText("Nữ");

            jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
            jLabel6.setText("Địa chỉ");

            txtDiaChi.setColumns(20);
            txtDiaChi.setRows(5);
            jScrollPane1.setViewportView(txtDiaChi);

            jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
            jLabel7.setText("Lương");

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtSdt)))
                    .addGap(41, 41, 41)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnNu)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7))
                        .addComponent(jLabel5)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnNam)
                            .addGap(51, 51, 51)
                            .addComponent(jLabel6)))
                    .addGap(10, 10, 10)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                        .addComponent(txtLuong)))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(25, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnNam)
                                .addComponent(jLabel6))
                            .addGap(18, 18, 18)
                            .addComponent(btnNu))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))))
                    .addGap(0, 0, Short.MAX_VALUE))
            );

            btnThem.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
            btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doanjava1/icon_ThemKH.png"))); // NOI18N
            btnThem.setText("Thêm nhân viên");
            btnThem.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnThemActionPerformed(evt);
                }
            });

            btnHuy.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
            btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon_no.png"))); // NOI18N
            btnHuy.setText("Hủy");
            btnHuy.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnHuyActionPerformed(evt);
                }
            });

            btnSua.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
            btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doanjava1/icon_Sua.png"))); // NOI18N
            btnSua.setText("Sửa thông tin");
            btnSua.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnSuaActionPerformed(evt);
                }
            });

            btnXoa.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
            btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doanjava1/icon_Xoa.png"))); // NOI18N
            btnXoa.setText("Xóa");
            btnXoa.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnXoaActionPerformed(evt);
                }
            });

            tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "Mã NV", "Tên nhân viên", "Giới tính", "Địa chỉ", "Số điện thoại", "Lương"
                }
            ));
            tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    tblNhanVienMouseClicked(evt);
                }
            });
            jScrollPane2.setViewportView(tblNhanVien);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(254, 254, 254)
                            .addComponent(jLabel1)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnThem)
                            .addGap(35, 35, 35)
                            .addComponent(btnHuy)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSua)
                            .addGap(18, 18, 18)
                            .addComponent(btnXoa))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane2)))
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnThem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHuy)
                            .addComponent(btnSua)
                            .addComponent(btnXoa)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void txtTenNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenNVActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
              try {
            if(txtDiaChi.getText().isEmpty()||txtLuong.getText().isEmpty()||txtMaNV.getText().isEmpty()
                 )
            {
           JOptionPane.showMessageDialog(null, "Vui lòng nhập đủ thông tin");
        }
           else
            {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String connectionUrl = "jdbc:sqlserver://DESKTOP-QEN4LJI;databaseName=QLTHUEXE;user=sa;password=12";
            Connection con = DriverManager.getConnection(connectionUrl);
            String query  ="INSERT into NV(MANV,TENNV,DIACHI,SDT,GT,LUONG) values (?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareCall(query);
             pst.setString(1, txtMaNV.getText().toUpperCase());
             pst.setString(2, txtTenNV.getText());
             pst.setString(3, txtDiaChi.getText());
             pst.setString(4, txtSdt.getText());
               if(btnNam.isSelected())
            {
                gt="Nam";
            }
            
             if(btnNu.isSelected())
            {
                gt="Nữ";
            }
            pst.setString(5, gt);
            pst.setString(6, txtLuong.getText());
            txtDiaChi.setText("");
            txtLuong.setText("");
            txtMaNV.setText("");
            txtSdt.setText("");
            txtTenNV.setText("");
            pst.execute();
            JOptionPane.showMessageDialog(null, "Thêm nhân viên thành công");
            DefaultTableModel model = (DefaultTableModel) tblNhanVien.getModel();
            model.setRowCount(0);
            show_NV();
            }
        } catch (Exception e) {
          JOptionPane.showMessageDialog(null, "Thêm nhân viên không thành công");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
         txtDiaChi.setText("");
            txtLuong.setText("");
            txtMaNV.setText("");
            txtSdt.setText("");
            txtTenNV.setText("");
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
                try {
            if(txtDiaChi.getText().isEmpty()||txtLuong.getText().isEmpty()||txtMaNV.getText().isEmpty()
                 )
            {
           JOptionPane.showMessageDialog(null, "Vui lòng nhập đủ thông tin");
        }
           else
            {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String connectionUrl = "jdbc:sqlserver://DESKTOP-QEN4LJI;databaseName=QLTHUEXE;user=sa;password=12";
            Connection con = DriverManager.getConnection(connectionUrl);
            
              String manv= txtMaNV.getText().toUpperCase();
             String tennv= txtTenNV.getText();
             String diachi= txtDiaChi.getText();
             String sdt= txtSdt.getText();
               if(btnNam.isSelected())
            {
                gt="Nam";
            }
            
             if(btnNu.isSelected())
            {
                gt="Nữ";
            }
           
            String luong= txtLuong.getText();
             String query  ="UPDATE NV SET MANV='"+manv+"',TENNV='"+tennv+"',DIACHI='"+diachi+"',SDT='"+sdt+"',GT='"+gt+"',LUONG='"+luong+"' WHERE MANV='"+manv +"'";
            txtDiaChi.setText("");
            txtLuong.setText("");
            txtMaNV.setText("");
            txtSdt.setText("");
            txtTenNV.setText("");
            PreparedStatement pst = con.prepareCall(query);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Sửa nhân viên thành công");
            DefaultTableModel model = (DefaultTableModel) tblNhanVien.getModel();
            model.setRowCount(0);
            show_NV();
            }
        } catch (Exception e) {
          JOptionPane.showMessageDialog(null, "Sửa nhân viên không thành công");
        }
        
    }//GEN-LAST:event_btnSuaActionPerformed

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
            int row = tblNhanVien.getSelectedRow();
            String manv = (tblNhanVien.getModel().getValueAt(row, 0).toString());
            String tennv = (tblNhanVien.getModel().getValueAt(row, 1).toString());
            String gt = (tblNhanVien.getModel().getValueAt(row, 2).toString());
            String diachi = (tblNhanVien.getModel().getValueAt(row, 3).toString());
            String sdt = (tblNhanVien.getModel().getValueAt(row, 4).toString());
            String luong = (tblNhanVien.getModel().getValueAt(row, 5).toString());
            txtMaNV.setText(manv);
            txtTenNV.setText(tennv);
            if(gt.equals("Nam"))
            {
                btnNam.isSelected();
            }
            else
            {
                btnNu.isSelected();
            }
            txtDiaChi.setText(diachi);
            txtLuong.setText(luong);
            txtSdt.setText(sdt);
    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
              try {
            if(txtDiaChi.getText().isEmpty()||txtLuong.getText().isEmpty()||txtMaNV.getText().isEmpty()
                 )
            {
           JOptionPane.showMessageDialog(null, "Vui lòng nhập đủ thông tin");
        }
           else
            {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String connectionUrl = "jdbc:sqlserver://DESKTOP-QEN4LJI;databaseName=QLTHUEXE;user=sa;password=12";
            Connection con = DriverManager.getConnection(connectionUrl);
            
              String manv= txtMaNV.getText().toUpperCase();
           
            String luong= txtLuong.getText();
             String query  ="DELETE NV WHERE MANV='"+manv +"'";
            txtDiaChi.setText("");
            txtLuong.setText("");
            txtMaNV.setText("");
            txtSdt.setText("");
            txtTenNV.setText("");
            PreparedStatement pst = con.prepareCall(query);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Xóa nhân viên thành công");
            DefaultTableModel model = (DefaultTableModel) tblNhanVien.getModel();
            model.setRowCount(0);
            show_NV();
            }
        } catch (Exception e) {
          JOptionPane.showMessageDialog(null, "Xóa nhân viên không thành công");
        }
        
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JRadioButton btnNam;
    private javax.swing.JRadioButton btnNu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextArea txtDiaChi;
    private javax.swing.JTextField txtLuong;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtTenNV;
    // End of variables declaration//GEN-END:variables
}
